spring.application.name=RestController

# PageHelper configuration
# pagehelper? ??? ??? ??? ?? ??
pagehelper.helperDialect=mysql
# pagehelper? ??? ??, ?? ? ?? ???? ?? ?????.
pagehelper.reasonable=true
# ???? ??? ??? ??, ??? ?????.
pagehelper.supportMethodsArguments=true
# pagenation ???? ???? ????? ?????. ???? ? ??? ?? ???? SQL ??? ?????.
pagehelper.params=count=countSql