plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.8-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.coffee.server'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(23)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
//	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.4'
//	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
//	pageHelper 의존성 버전이 1.4.3이면 완전 엉터리가 됨. 작동하긴함. 근데 저 버전은 AI가 나한테 준거임 ㅡ.ㅡ AI는 어쩔땐 엉터리임 명심.
	implementation 'com.github.pagehelper:pagehelper-spring-boot-starter:1.4.6'
}

//implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
//implementation 'org.springframework.boot:spring-boot-starter-web'
//implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
//compileOnly 'org.projectlombok:lombok'
//developmentOnly 'org.springframework.boot:spring-boot-devtools'
//runtimeOnly 'com.mysql:mysql-connector-j'
//annotationProcessor 'org.projectlombok:lombok'
//testImplementation 'org.springframework.boot:spring-boot-starter-test'
//testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.4'
//testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

tasks.named('test') {
	useJUnitPlatform()
}
